version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: subtitle
      POSTGRES_PASSWORD: subtitle
      POSTGRES_DB: subtitle_editor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://subtitle:subtitle@postgres:5432/subtitle_editor
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

volumes:
  postgres_data: